apiVersion: v1
kind: ServiceAccount
metadata:
  name: url-shortener-api
  namespace: url-shortener
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::831963379503:role/url-shortener-api-dynamodb
